{
    'name': 'Project Extension',
    'author': 'Confianz IT',
    'licence': 'LGPL-v3',
    'summary': 'Project Extension',
    'description': """""",
    'maintainer': 'Confianz IT',
    'category': 'project',
    'website': 'https://www.confianzit.com',
    'depends': ['project', 'crm', 'account', 'hr', 'hr_timesheet', 'mail','bus' ],
    'data': [
                'wizards/user_proposal_wizard.xml',
                'wizards/project_invoice_wizard.xml',
                'wizards/wbs_template_picker_wizard.xml',
                'views/wbs_project_view.xml',
                'views/project.xml',
                'views/crm_lead.xml',
                'views/proposal_version.xml',
                'views/project_milestone.xml',
                'security/project_security.xml',
                'security/ir.model.access.csv',
                'data/mail_template.xml',
                'data/stage_data.xml',
                'data/cron.xml',
                'views/project_portal_templates.xml',
                'views/proposal_portal_templates.xml',
                'views/account_invoice.xml',
                'views/project_task.xml',
                'views/account_analytic_line.xml',
                'views/hr_employee.xml',
                'views/assets_backend.xml',
                'views/hr_timesheet_templates.xml',
                'report/external_report_layout.xml',
                'report/report_invoice.xml',
                'data/demo_data.xml',
            ],
    'qweb': [
        'static/src/xml/timesheet_plan.xml',
    ],
#    "external_dependencies": {"python": ['inscriptis'], "bin": []},
    'uninstall_hook': "uninstall_hook",
    'installable': True,
    'auto_install': False,
    'application': False,
    'post_init_hook': '_update_base_values'
}
