from . import project
from . import crm_lead
from . import proposal_version
from . import project_task
from . import mail_thread
from . import project_milestone
from . import account_invoice
from . import account_analytic_line
from . import mail_compose_message
from . import hr_employee
from . import wbs_project
